//export const ROOTURL = "http://localhost:3001"
export const ROOTURL = "http://uns1.herokuapp.com"
export const LOGINURL = ROOTURL + "/users/sign_in"
export const LOGOUTURL = ROOTURL + "/users/sign_out"
export const ALLPROFILESURL = ROOTURL + "/profiles.json"
export const PROFILEURL = ROOTURL + "/profiles"
export const REGISTERURL = ROOTURL + "/users/register"
export const FORGOTUSERNAMEURL = ROOTURL + "/send_username"
export const SAVEUSERURL = ROOTURL + "/users"
export const RESETPASSWORDURL = ROOTURL + "/users/password/edit"
export const UPLOADAVATARURL = ROOTURL + "/attachment/photosave"
// Account setting URLs
export const VALIDUSERNAMEURL = ROOTURL + "/account_settings/valid_username"
export const SAVEUSERNAMEURL = ROOTURL + "/account_settings/change_username"
export const SAVEEMAILURL = ROOTURL + "/account_settings/change_email"
export const SAVEDOBURL = ROOTURL + "/account_settings/change_dob"

