//export const ROOTURL = "http://localhost:3001"
export const ROOTURL = "http://uns1.herokuapp.com"
export const LOGINURL = ROOTURL + "/users/sign_in"
export const LOGOUTURL = ROOTURL + "/users/sign_out"
export const ALLPROFILESURL = ROOTURL + "/profiles.json"
export const PROFILEURL = ROOTURL + "/profiles"
