//export const ROOTURL = "http://localhost:3001"
export const ROOTURL = "https://uns1.herokuapp.com"
export const LOGINURL = ROOTURL + "/users/sign_in"
export const LOGOUTURL = ROOTURL + "/users/sign_out"
export const ALLPROFILESURL = ROOTURL + "/profiles.json"
export const PROFILEURL = ROOTURL + "/profiles"
export const REGISTERURL = ROOTURL + "/users"
export const ABOUTURL = ROOTURL + "/users/about"
export const ABOUTROUTEDURL = ROOTURL + "/users/aboutRouted"
export const FORGOTUSERNAMEURL = ROOTURL + "/send_username"
export const SAVEUSERURL = ROOTURL + "/users"
export const RESETPASSWORDURL = ROOTURL + "/users/password/edit"
export const UPLOADAVATARURL = ROOTURL + "/attachment/photosave"
// Account setting URLs
export const VALIDUSERNAMEURL = ROOTURL + "/account_settings/valid_username"
export const SAVEUSERNAMEURL = ROOTURL + "/account_settings/change_username"
export const VALIDEMAILURL = ROOTURL + "/account_settings/valid_email"
export const SAVEEMAILURL = ROOTURL + "/account_settings/change_email"
export const SAVEDOBURL = ROOTURL + "/account_settings/change_dob"
export const SAVEZIPCODEURL = ROOTURL + "/account_settings/change_zipcode"
export const SAVEPASSWORDURL = ROOTURL + "/account_settings/update_password"
export const SAVEPHONEURL = ROOTURL + "/account_settings/change_phone"
export const VALIDPHONEURL = ROOTURL + "/account_settings/valid_phone"


